const track = {
  album: {
    album_type: "SINGLE",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/4o4tLTIJ3eWMFerz73atcT"
        },
        href: "https://api.spotify.com/v1/artists/4o4tLTIJ3eWMFerz73atcT",
        id: "4o4tLTIJ3eWMFerz73atcT",
        name: "Qveen Herby",
        type: "artist",
        uri: "spotify:artist:4o4tLTIJ3eWMFerz73atcT"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/76Y7NZJC5RZQ5rxGVSMDTI"
    },
    href: "https://api.spotify.com/v1/albums/76Y7NZJC5RZQ5rxGVSMDTI",
    id: "76Y7NZJC5RZQ5rxGVSMDTI",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b2736308676ccd021c1d6723afff",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e026308676ccd021c1d6723afff",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d000048516308676ccd021c1d6723afff",
        width: 64
      }
    ],
    name: "EP 7",
    release_date: "2019-11-05",
    release_date_precision: "day",
    total_tracks: 5,
    type: "album",
    uri: "spotify:album:76Y7NZJC5RZQ5rxGVSMDTI"
  },
  artists: [
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/4o4tLTIJ3eWMFerz73atcT"
      },
      href: "https://api.spotify.com/v1/artists/4o4tLTIJ3eWMFerz73atcT",
      id: "4o4tLTIJ3eWMFerz73atcT",
      name: "Qveen Herby",
      type: "artist",
      uri: "spotify:artist:4o4tLTIJ3eWMFerz73atcT"
    }
  ],
  available_markets: [
    "AD",
    "AE",
    "AR",
    "AT",
    "AU",
    "BE",
    "BG",
    "BH",
    "BO",
    "BR",
    "CA",
    "CH",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DE",
    "DK",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FR",
    "GB",
    "GR",
    "GT",
    "HK",
    "HN",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JO",
    "JP",
    "KW",
    "LB",
    "LI",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MT",
    "MX",
    "MY",
    "NI",
    "NL",
    "NO",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PH",
    "PL",
    "PS",
    "PT",
    "PY",
    "QA",
    "RO",
    "SA",
    "SE",
    "SG",
    "SK",
    "SV",
    "TH",
    "TN",
    "TR",
    "TW",
    "US",
    "UY",
    "VN",
    "ZA"
  ],
  disc_number: 1,
  duration_ms: 138454,
  explicit: true,
  external_ids: {
    isrc: "QM24S1925278"
  },
  external_urls: {
    spotify: "https://open.spotify.com/track/1xMtCg3FpZ29WvusY1UkvE"
  },
  href: "https://api.spotify.com/v1/tracks/1xMtCg3FpZ29WvusY1UkvE",
  id: "1xMtCg3FpZ29WvusY1UkvE",
  is_local: false,
  name: "Pink Cadillac",
  popularity: 41,
  preview_url: "https://p.scdn.co/mp3-preview/a534966d4b869ba22948ffc6d6ebde8879c67b4b?cid=589e96bcdcbb45e0a1424061ed9d4be8",
  track_number: 2,
  type: "track",
  uri: "spotify:track:1xMtCg3FpZ29WvusY1UkvE"
}

export default track;